version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    working_dir: /var/www
    volumes:
    - ./:/var/www/
    env_file:
    - docker/.environment
    expose:
    - "9000"

  # The Web Server
  web:
    build:
      context: ./
      args:
        - PHP_UPSTREAM_CONTAINER=app
        - PHP_UPSTREAM_PORT=9000
      dockerfile: docker/web.dockerfile
    working_dir: /var/www/
    volumes:
    - ./:/var/www
    volumes_from:
    - app
    ports:
    - 8081:81
    depends_on:
    - database
    - app

  # The Database
  database:
    env_file:
    - docker/.environment
    build:
      context: ./
      dockerfile: docker/database.dockerfile
    ports:
    - "33062:3306"

  redis:
    image: redis:4.0.8
    ports:
      - "63791:6379"

  composer:
    image: composer:latest
    restart: 'no'
    volumes:
    - ./:/app/api
    command:
      --working-dir=api install --ignore-platform-reqs
    depends_on:
    - app